spring:      
  datasource:
    url: jdbc:h2:mem:licensedb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
eureka:
  instance:
    ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true  
    service-url:
      default-zone: http://localhost:8761/eureka/      
